### ISSUE TITLE
Fix for 'missing' populated objects

### ISSUE THREAD

**Issue by ChrisTerBeke** [Prismatik/mongoose-reverse-populate#2]
To get the populated objects in your object directly, just change this:

```
var reversePopulate = require('mongoose-reverse-populate');

//the next step requires access to the 'Author' and 'Post' mongoose model

Author.find().exec(function(err, authors) {
    reversePopulate(authors, "posts", true, Post, "author", function(err, popAuthors) {
        //popAuthors will be populated with posts under .posts property
    });
});
```

to this:

```
var reversePopulate = require('mongoose-reverse-populate');

//the next step requires access to the 'Author' and 'Post' mongoose model

Author.find().lean().exec(function(err, authors) {
    reversePopulate(authors, "posts", true, Post, "author", function(err, popAuthors) {
        //popAuthors will be populated with posts under .posts property
    });
});
```

Notice the .lean() command after .find(). This returns a directly editable javascript object instead of a mongoose schema, and in here, the .posts property is directly accessible.

**Comment by s-taylor** [comment]
Thanks Chris, this is definitely an option but the downside in doing this would be you could no longer call the schema methods i.e. save. I think it's useful to make these available as you might want to change a model after it being populated.

**Comment by ChrisTerBeke** [comment]
I think you can just leave it like this and add this as a suggestion in the readme instead of the (kinda ugly) construction of needing to loop over the results and call a single nested document from there.

**Comment by s-taylor** [comment]
At some stage I'll find out how to actually attach the models so that they log correctly. I know it's possible as KeystoneJS does this with its populateRelated function, but I just haven't looked into the implementation.
